# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: gentle-brook-21149.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        serviceUrl:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        maximumPoolSize: 10
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
